---
title: "Job_attrition"
output: html_document
---
# 1. Import Data
```{r}
library(tidyverse)
library(data.table)
```

```{r}
path="WA_Fn-UseC_-HR-Employee-Attrition.csv"
data <- fread(path)
data
```


```{r}
class(data)
dim(data)
str(data)
```

# 2. Descriptive statistics

```{r}
summary(data)
```

```{r}
psych::describe(data)
```
# 3. Check NA value

```{r}
sum(is.na(data))
```


```{r}
#install.packages("Tmisc")
library(Tmisc)
Tmisc::gg_na(data)
```


```{r}
Tmisc::propmiss(data)
```
```{r}
count(data,Attrition)
```
# 4. Data visualization

```{r}
ggplot(data,aes(x = Age,fill = Attrition)) +
  geom_density(alpha = 0.4) 
```

```{r}
head(data)
```

```{r}
ggplot(data,aes(x = Attrition,y = Age,fill=Attrition)) +
  geom_boxplot(alpha = 0.4) 
```


```{r}
ggplot(data, aes(x = BusinessTravel)) + 
  geom_bar()
```
```{r}
count(data,BusinessTravel)
```
```{r}
#install.packages("memisc")
library(memisc)
memisc::percent(data$BusinessTravel)
```



```{r}
ggplot(data, 
       aes(x = BusinessTravel, 
           y = ..count.. / sum(..count..))) + 
  geom_bar()
```


```{r}
plotdata <- data %>%
  count(BusinessTravel) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
plotdata
```


```{r}
library(scales)
ggplot(plotdata, 
       aes(x = reorder(BusinessTravel, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           #fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Race", 
       y = "Percent", 
       title  = "Participants by race")
```

```{r}
# create a summary dataset
library(dplyr)
plotdata <- data %>%
  group_by(Attrition, BusinessTravel) %>%
  summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct))
plotdata
```


```{r}
# create segmented bar chart
# adding labels to each segment

ggplot(plotdata, 
       aes(x = Attrition,
           y = pct,
           fill = BusinessTravel)) + 
  geom_bar(stat = "identity",
           position = "fill") +
  scale_y_continuous(breaks = seq(0, 1, .2),label = percent) +
  geom_text(aes(label = lbl), 
            size = 3, 
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set2") +
  #labs(y = "Percent",fill = "Drive Train",x = "Class",title = "Automobile Drive by Class") +
  theme_minimal()
```


```{r}
data %>%
  group_by(Attrition, BusinessTravel) %>%
  summarize(n = n()) %>% 
  mutate(pct = n/sum(n),lbl = scales::percent(pct)) %>% 
  ggplot(aes(x = Attrition,y = pct,
           fill = BusinessTravel)) + 
  geom_bar(stat = "identity",
           position = "fill") +
  scale_y_continuous(breaks = seq(0, 1, .2),label = percent) +
  geom_text(aes(label = lbl), 
            size = 3, 
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set2") +
  #labs(y = "Percent",fill = "Drive Train",x = "Class",title = "Automobile Drive by Class") +
  theme_minimal()
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

