---
title: "Untitled"
output: html_document
---
```{r}
# LEARNING LAB 24: A/B TESTING & STATISTICAL INFERENCE ----
# WEB TRAFFIC CONVERSION A/B TESTING ----

# LIBRARIES ----

# Core
library(tidyverse)
library(tidyquant)
library(lubridate)
library(plotly)
```


```{r}
# EDA
library(skimr)

# Modeling & Inference
library(infer)

# Plotting & Conversion Calculations
source("utils_ab_testing_conversions.R")
```


```{r}
# 1.0 Data ----

ab_data_raw_tbl <- read_csv("data/ab_data.csv")

ab_data_raw_tbl %>% skim()
```

```{r}
calculate_conversion <- function(data, ...) {
    
    groups_expr <- enquos(...)
    
    data %>%
        group_by(!!! groups_expr) %>%
        summarize(
            count      = n(),
            conversion = sum(converted),
            prop       = conversion / count
        ) %>%
        ungroup()
    
}
```

```{r}
# 2.0 EDA ----

# 2.1 Landing Page & Groups ----

ab_data_raw_tbl

ab_data_raw_tbl %>% calculate_conversion()
```


```{r}
# Landing Page - Old vs New
ab_data_raw_tbl %>% calculate_conversion(landing_page)
```


```{r}
# Group - Control vs Treatment
ab_data_raw_tbl %>% calculate_conversion(group)
```
```{r}
plot_conversion_heatmap <- function(data, .x, .y, 
                                    labs_title = "Conversion Heatmap") {

    x_expr <- enquo(.x)
    y_expr <- enquo(.y)
    
    
    g <- data %>%
        mutate(label = str_glue("Conv Pct: {scales::percent(prop, accuracy = 0.1)}
                                Converted: {scales::comma(conversion)}
                                Total: {scales::comma(count)}")) %>%
        
        ggplot(aes(x = !!x_expr, y = !!y_expr, fill = prop)) +
        geom_tile() +
        geom_text(aes(label = label), color = "white") +
        theme_tq() +
        theme(legend.position = "none") +
        labs(title = labs_title)
    
    # ggplotly(g, tooltip = "text")
    
    g
}
```


```{r}
# Landing Page & Group
ab_data_raw_tbl %>% calculate_conversion(group, landing_page)

ab_data_raw_tbl %>% 
    calculate_conversion(group, landing_page) %>%
    plot_conversion_heatmap(group, landing_page, 
                            labs_title = "A/B Testing Conversion Heatmap")
```


```{r}
# 2.2 Conversion Over Time ----

comparison_1 <- c("control-old_page", "treatment-new_page")
comparison_2 <- c("control-new_page", "treatment-old_page")
```
```{r}
calculate_conversion_vs_time <- function(data, ..., unit = "day") {
    
    groups_expr <- enquos(...)
    
    data %>%
        mutate(date = floor_date(timestamp, unit = unit)) %>%
        group_by(!!!groups_expr, date) %>%
        summarize(
            count      = n(),
            conversion = sum(converted),
            prop       = conversion / count
        ) %>%
        ungroup()
    
}
```

```{r}
plot_conversion_vs_time <- function(data, ..., 
                                    loess = TRUE, loess_span = 0.3, loess_se = TRUE,
                                    labs_title = "Conversion Over Time", 
                                    labs_y = "Conversion (%)", labs_x = "") {
    
    g <- data %>%
        ggplot(aes(date, prop, ...)) +
        geom_line() +
        expand_limits(y = 0) +
        scale_y_continuous(labels = scales::percent_format()) +
        theme_tq() +
        scale_color_tq() +
        labs(title = labs_title, y = labs_y, x = labs_x) 
    
    if (loess) g <- g + geom_smooth(method = "loess", span = loess_span, se = loess_se)
    
    ggplotly(g)
}
```

```{r}
# Comparison 1: Control + Old Page vs Treatment + New Page
# - Majority of Traffic
ab_data_raw_tbl %>%
    calculate_conversion_vs_time(group, landing_page, unit = "1 day") %>%
    mutate(label = str_c(group, landing_page, sep = "-")) %>%
    filter(label %in% comparison_1) %>%
    plot_conversion_vs_time(color = label, loess = TRUE, loess_se = FALSE,
                            labs_title = "Conversion Over Time - Majority of Traffic")
```


```{r}
# Comparison 2: Control + New Page vs Treatment + Old Page
# - Minority of Traffic
ab_data_raw_tbl %>%
    calculate_conversion_vs_time(group, landing_page, unit = "1 day") %>%
    mutate(label = str_c(group, landing_page, sep = "-")) %>%
    filter(label %in% comparison_2) %>%
    plot_conversion_vs_time(color = label, loess = TRUE, loess_se = FALSE, loess_span = 0.6)
```


```{r}
# 3.0 Feature Engineering ----

# 3.1 Combine Group & Landing Page
ab_data_tbl <- ab_data_raw_tbl %>%
    mutate(label = str_c(group, landing_page, sep = "-")) %>%
    filter(label %in% comparison_1) %>%
    select(user_id, timestamp, label, converted)
ab_data_tbl
```


```{r}
# 4.0 DISTRIBUTION ANALYSIS ----

ab_data_tbl %>%
    calculate_conversion_vs_time(label, unit = "day") %>%
    ggplot(aes(prop)) +
    geom_histogram(bins = 100) +
    facet_wrap(~ label)
```


```{r}
# 5.0 DIFFERENCE IN MEANS ----

# - Assumption: Conversion rate is independent of date 
#   - This assumption is not valid for total web traffic, conversion counts, etc since date may influence
#   - This assumption is valid for conversion rates, which should be constant if visits are large enough

# - Hypothesis Testing: https://moderndive.com/9-hypothesis-testing.html
#   - Want to understand if mean of Conversions for Treatment-New Page is different than Control-Old Page
#   - Test for difference in means

# 5.1 Majority Traffic: Treatment_NewPage vs Control_OldPage ----

comparison_1_tbl <- ab_data_tbl %>%
    filter(label %in% comparison_1) %>%
    calculate_conversion_vs_time(label, unit = "1 day")
comparison_1_tbl
```


```{r}
comparison_1_tbl %>% plot_conversion_vs_time(color = label, loess_se = FALSE)
```


```{r}
comparison_1_tbl %>%
    ggplot(aes(prop)) +
    geom_histogram(bins = 20) +
    facet_wrap(~ label, ncol = 1)

```


```{r}
# No Permutation - Get the mean difference in daily conversion rate
comp_1_diff_means <- comparison_1_tbl %>%
    
    # Infer
    specify(prop ~ label) %>%
    calculate(stat  = "diff in means", 
              order = c("treatment-new_page", "control-old_page"))

comp_1_diff_means
```


```{r}
# Permutation - Find *P-Value* in Mean Difference ----
# - Why? Cannot trust a point estimate - Sample Variation
# - Goal: Prove difference in mean conversion rate between Treatment-New Page vs Control-Old Page
# - Use Permutation = Sample *without* replacement
# - Calculate P-Value of Hypothesis:
# - H0 (Null): Improvement is <= 1%
# - H1 (Alt): Improvement is > 1%

comp_1_diff_means_permuted_tbl <- comparison_1_tbl %>%
    
    # Infer
    specify(prop ~ label) %>%
    hypothesize(null = "independence") %>%
    generate(reps = 1000, type = "permute") %>%
    calculate(stat = "diff in means", 
              order = c("treatment-new_page", "control-old_page")) 
comp_1_diff_means_permuted_tbl
```


```{r}
comp_1_diff_means_permuted_tbl %>%
    visualize() +
    shade_p_value(obs_stat = 0.01, direction = "right")
```

```{r}
comp_1_diff_means_permuted_tbl %>% 
    get_p_value(obs_stat = 0.0, direction = "right")
```
```{r}
# Bootstrap - Find True Distribution & Confidence Intervals ----
# - Permutation - Gave us P-Value, reject difference in mean
# - What about distribution of mean differences?
# - Goal: Confidence Intervals & Distribution - Use Bootstrap
# - Sample *with* replacement
comp_1_diff_bootstrap_tbl <- comparison_1_tbl %>%
    
    # Infer
    specify(prop ~ label) %>%
    
    # Remove Hypothesis:
    # hypothesize(null = "independence") %>%
    
    # Change generate(): type = "boostrap"
    generate(reps = 1000, type = "bootstrap") %>%
    calculate(stat = "diff in means", 
              order = c("treatment-new_page", "control-old_page"))
comp_1_diff_bootstrap_tbl
```


```{r}
bootstrap_ci_tbl <- comp_1_diff_bootstrap_tbl %>%
    get_confidence_interval(level = 0.95, type = "percentile")
bootstrap_ci_tbl
```


```{r}
comp_1_diff_bootstrap_tbl %>%
    visualize() +
    shade_confidence_interval(endpoints = bootstrap_ci_tbl) +
    geom_vline(xintercept = comp_1_diff_means$stat, color = "red")
comp_1_diff_bootstrap_tbl
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

