---
title: "Untitled"
output: html_document
---
#**Data Visualization**
```{r}
#install.packages("mosaicData")
library(ggplot2)
data(Marriage, package = "mosaicData")
Marriage

```

```{r}
# plot the distribution of race
ggplot(Marriage, aes(x = race)) + 
  geom_bar()
```

```{r}
# plot the distribution as percentages
ggplot(Marriage, 
       aes(x = race, 
           y = ..count.. / sum(..count..))) + 
  geom_bar() +
  labs(x = "Race", 
       y = "Percent", 
       title  = "Participants by race") +
  scale_y_continuous(labels = scales::percent)
```


```{r}
# calculate number of participants in 
# each race category
library(dplyr)
plotdata <- Marriage %>%
 count(race)
plotdata
```


```{r}
# plot the bars in ascending order
ggplot(plotdata, 
       aes(x = reorder(race, n), 
           y = n)) + 
  geom_bar(stat = "identity") +
  labs(x = "Race", 
       y = "Frequency", 
       title  = "Participants by race")
```


```{r}
library(dplyr)
library(scales)
plotdata <- Marriage %>%
  count(race) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))
plotdata
```


```{r}
# plot the bars as percentages, 
# in decending order with bar labels
ggplot(plotdata, 
       aes(x = reorder(race, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Race", 
       y = "Percent", 
       title  = "Participants by race")
```


```{r}
library(ggplot2)
mpg

```


```{r}
# stacked bar chart
ggplot(mpg, 
       aes(x = class, 
           fill = drv)) + 
  geom_bar(position = "stack")
```


```{r}
# create a summary dataset
library(dplyr)
plotdata <- mpg %>%
  group_by(class, drv) %>%
  summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct))
plotdata
```


```{r}
# create segmented bar chart
# adding labels to each segment

ggplot(plotdata, 
       aes(x = factor(class,
                      levels = c("2seater", "subcompact", 
                                 "compact", "midsize", 
                                 "minivan", "suv", "pickup")),
           y = pct,
           fill = factor(drv, 
                         levels = c("f", "r", "4"),
                         labels = c("front-wheel", 
                                    "rear-wheel", 
                                    "4-wheel")))) + 
  geom_bar(stat = "identity",
           position = "fill") +
  scale_y_continuous(breaks = seq(0, 1, .2), 
                     label = percent) +
  geom_text(aes(label = lbl), 
            size = 3, 
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set2") +
  labs(y = "Percent", 
       fill = "Drive Train",
       x = "Class",
       title = "Automobile Drive by Class") +
  theme_minimal()
```


```{r}
ggplot(plotdata, 
       aes(x = class,
           y = pct,
           fill = drv)) + 
  geom_bar(stat = "identity",
           position = "fill") +
  #scale_y_continuous(breaks = seq(0, 1, .2),label = percent) +
  geom_text(aes(label = lbl), 
            size = 3, 
            position = position_stack(vjust = 0.5)) +
  scale_fill_brewer(palette = "Set2") +
  #labs(y = "Percent",fill = "Drive Train",x = "Class",title = "Automobile Drive by Class") +
  theme_minimal()
```
```{r}
data(Salaries, package="carData")
Salaries
```


```{r}
# calculate means and standard errors by rank and sex

plotdata <- Salaries %>%
  group_by(rank, sex) %>%
  summarize(n = n(),
            mean = mean(salary),
            sd = sd(salary),
            se = sd/sqrt(n))

# plot the means and standard errors by sex
ggplot(plotdata, aes(x = rank,
                     y = mean, 
                     group=sex, 
                     color=sex)) +
  geom_point(size = 3) +
  geom_line(size = 1) +
  geom_errorbar(aes(ymin  =mean - se, 
                    ymax = mean+se), 
                width = .1)
```
```{r}
devtools::install_github("ricardo-bion/ggradar", 
                          dependencies = TRUE)
```


```{r}

data(msleep, package = "ggplot2")
library(ggradar)
library(scales)
library(dplyr)
library(ggplot2)

plotdata <- msleep %>%
  filter(name %in% c("Cow", "Dog", "Pig")) %>%
  dplyr::select(name, sleep_total, sleep_rem, 
         sleep_cycle, brainwt, bodywt) %>%
  rename(group = name) %>%
  mutate_at(vars(-group),
            funs(rescale))
plotdata
```


```{r}
# generate radar chart
ggradar::ggradar(plotdata, 
                grid.label.size = 4,
                axis.label.size = 4, 
                group.point.size = 5,
                group.line.width = 1.5,
                legend.text.size= 10) +
                labs(title = "Mammals, size, and sleep")
```
```{r}
library(ggradar)
library(dplyr)
library(scales)
library(tibble)
mtcars

```
```{r}
mtcars_radar <- mtcars %>% 
  as_tibble(rownames = "group") %>% 
  mutate_at(vars(-group), rescale) %>% 
  tail(4) %>% 
  select(1:10)
mtcars_radar
```


```{r}
ggradar(mtcars_radar)
```


```{r}
# Library
library(fmsb)
 
# Create data: note in High school for several students
set.seed(99)
data <- as.data.frame(matrix( sample( 0:20 , 15 , replace=F) , ncol=5))
colnames(data) <- c("math" , "english" , "biology" , "music" , "R-coding" )
rownames(data) <- paste("mister" , letters[1:3] , sep="-")
 
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each variable to show on the plot!
data <- rbind(rep(20,5) , rep(0,5) , data)
data
```


```{r}
# Color vector
colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )

# plot with default options:
radarchart( data  , axistype=1 , 
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,5), cglwd=0.8,
    #custom labels
    vlcex=0.8 
    )

# Add a legend
legend(x=0.7, y=1, legend = rownames(data[-c(1,2),]), bty = "n", pch=20 , col=colors_in , text.col = "grey", cex=1.2, pt.cex=3)
```


```{r}
# Libraries
library(GGally)
library(dplyr)
#library(hrbrthemes)

# Data set is provided by R natively
data <- iris

# Plot
data %>%
  arrange(desc(Species)) %>%
  ggparcoord(
    columns = 1:4, groupColumn = 5, order = "anyClass",
    showPoints = TRUE, 
    title = "Original",
    alphaLines = 1
    ) + 
  scale_color_manual(values=c( "#69b3a2", "#E8E8E8", "#E8E8E8") ) +
  #theme_ipsum()+
  theme(
    legend.position="Default",
    plot.title = element_text(size=10)
  ) +
  xlab("")
```

# XGBOOST

```{r}
library(readxl)
library(tidyverse)
library(xgboost)
library(caret)
```


```{r}
power_plant = as.data.frame(read_excel("Folds5x2_pp.xlsx"))
dim(power_plant)
head(power_plant)
```


```{r}
str(power_plant)
```

```{r}
set.seed(100)  # For reproducibility
# Create index for testing and training data
inTrain <- createDataPartition(y = power_plant$PE, p = 0.8, list = FALSE)
# subset power_plant data to training
training <- power_plant[inTrain,]
# subset the rest to test
 testing <- power_plant[-inTrain,]
```


```{r}
X_train = xgb.DMatrix(as.matrix(training %>% select(-PE)))
y_train = training$PE
X_test = xgb.DMatrix(as.matrix(testing %>% select(-PE)))
y_test = testing$PE
```

```{r}
xgb_trcontrol = trainControl(
  method = "cv",
  number = 5,  
  allowParallel = TRUE,
  verboseIter = FALSE,
  returnData = FALSE
)
```

I am specifing the same parameters with the same values as I did for Python above. The hyperparameters to optimize are found in the website.
```{r}
xgbGrid <- expand.grid(nrounds = c(100,200),  # this is n_estimators in the python code above
                       max_depth = c(10, 15, 20, 25),
                       colsample_bytree = seq(0.5, 0.9, length.out = 5),
                       ## The values below are default values in the sklearn-api. 
                       eta = 0.1,
                       gamma=0,
                       min_child_weight = 1,
                       subsample = 1
                      )
```


```{r}
# PROBLEM with Xgtrain
set.seed(0) 
xgb_model = train(
  X_train, y_train,  
  trControl = xgb_trcontrol,
  tuneGrid = xgbGrid,
  method = "xgbTree"
)
```


```{r}
xgb_train$bestTune
```


```{r}
predicted = predict(xgb_model, X_test)
residuals = y_test - predicted
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
```


```{r}
predicted = predict(xgb_model, X_test)
residuals = y_test - predicted
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
```


```{r}
options(repr.plot.width=8, repr.plot.height=4)
my_data = as.data.frame(cbind(predicted = predicted,
                            observed = y_test))
# Plot predictions vs test data
ggplot(my_data,aes(predicted, observed)) + geom_point(color = "darkred", alpha = 0.5) + 
    geom_smooth(method=lm)+ ggtitle('Linear Regression ') + ggtitle("Extreme Gradient Boosting: Prediction vs Test Data") +
      xlab("Predecited Power Output ") + ylab("Observed Power Output") + 
        theme(plot.title = element_text(color="darkgreen",size=16,hjust = 0.5),
         axis.text.y = element_text(size=12), axis.text.x = element_text(size=12,hjust=.5),
         axis.title.x = element_text(size=14), axis.title.y = element_text(size=14))
```

```{r}
# Injecting missing value
set.seed(86)
iris[sample(1:nrow(iris), 5), "Sepal.Width"] <- NA
iris[sample(1:nrow(iris), 10), "Petal.Length"] <- NA
iris[sample(1:nrow(iris), 8), "Sepal.Length"] <- NA
iris
```


```{r}
# Using is.na() function
any(is.na(iris))
```


```{r}
# Using complete.cases() function to get percentage of missing value
nrow(iris[!complete.cases(iris), ])/nrow(iris)*100
```

```{r}
# Looking at the missing data pattern
library(mice)
md.pattern(iris)
```
```{r}
# Deleting missing observations
iris <- iris[complete.cases(iris), ]
# or we can use na.omit() function
iris <- na.omit(iris)
 
# Ignoring missing values while building lm model
lm(mpg ~ cyl + disp, data=mtcars, na.action=na.omit)
```


```{r}
## Removing columns with more than 30% NA
iris[, -which(colMeans(is.na(iris)) > 0.3)]
```


```{r}
# Using impute function from Hmisc package
library(Hmisc)
impute(iris$Sepal.Length, mean)  # replace with mean
impute(iris$Sepal.Length, median)  # median
```


```{r}
# Filling missing values with Mean
iris$Sepal.Length[is.na(iris$Sepal.Length)] = mean(iris$Sepal.Length, na.rm=TRUE)
# alternative way is to use ifelse
iris = transform(iris, y = ifelse(is.na(iris), mean(iris, na.rm=TRUE), Sepal.Length))
```


```{r}
library(mice)
# Imputing the values using mice
imputed_iris <- mice(iris, m=5, method = 'pmm', seed = 101)
# checking the summary
summary(imputed_iris)
```


```{r}
# Checking imputed values of sleep variable
imputed_iris$imp
```

